language: java
jdk:
  - openjdk8
services:
  - docker

before_install:
  - chmod +x mvnw
  - docker pull openjdk:8-jdk-alpine

script:
  - mvn test
  - mvn clean package

after_success:
  - docker build -t ryhor/multi-visit .
  - docker build -t ryhor/multi-nginx ./nginx
  - echo  "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push grinman/multi-visit:latest
  - docker push grinman/multi-nginx:latest

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-visit"
  env: "MultiVisit-env"
  bucket_name: "elasticbeanstalk-us-east-2-639392862171"
  bucket_path: "multi-visit"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY