sudo: required
language: java
jdk:
  - openjdk8
services:
  - docker

before_install:
  - chmod +x mvnw
  - docker pull openjdk:8-jdk-alpine

script:
  - mvn test
  - mvn clean package

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker-compose build
  - docker tag docker-tutorial_docker-test:latest grinman/docker-test:latest
  - docker push grinman/docker-test:latest

before_deploy:
  - mvn clean package

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-springboot-travis"
  env: "DockerSpringbootTravis-env"
  bucket_name: "elasticbeanstalk-us-east-2-639392862171"
  bucket_path: "docker-springboot-travis"
  skip_cleanup: true
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY