language: java
jdk:
  - openjdk8
services:
  - docker

before_install:
  - chmod +x mvnw
  - docker pull openjdk:8-jdk-alpine

script:
  - mvn test
  - mvn clean package

after_success:
  - docker build -t ryhor/docker-test .

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-springboot-travis"
  env: "DockerSpringbootTravis-env"
  bucket_name: "elasticbeanstalk-us-east-2-639392862171"
  bucket_path: "docker-springboot-travis"
  skip_cleanup: true
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY