version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=visitDB
      - POSTGRES_USER=ryhor
      - POSTGRES_PASSWORD=fmIZ3REf
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  visit:
    environment:
      - PGURL=jdbc:postgresql://postgres/visitDB
      - PGUSER=ryhor
      - PGPASSWORD=fmIZ3REf
    build: .
    depends_on:
      - postgres